name: share_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  animator: ^1.0.0+5
  cached_network_image: ^2.0.0
  cloud_firestore: ^0.13.4+2
  cupertino_icons: ^0.1.3
  firebase_storage: ^3.1.5
  firebase_auth: ^0.15.5+3
  firebase_messaging: ^6.0.13
  flutter_svg: ^0.17.3+1
  google_sign_in: ^4.4.0
  geolocator: ^5.3.1
  image_picker: ^0.6.4
  image: ^2.1.4
  path_provider: ^1.6.5
  timeago: ^2.0.26
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
